### ISSUE TITLE
NoWakeLock or DeepSleep ?

### ISSUE THREAD

**Issue by bolbolfolfol** [Jasper-1024/DeepSleep#8]
Hi
i saw that both block wakelocks
do i have to use both apps or just 1 ?
in case of one, which one do you suggest and thank you

**Comment by Jasper-1024** [comment]
deepsleep needs to be disabled by selecting the application in lsposed.  nowakelock only needs to select the system framework.

In principle, deepsleep disables wakelock applications when applied directly from within the application. nowakelock is disabled when the wake-up lock application process is in the system framework.

Suggestions for use

- deepsleep is easier to use, if you can meet your needs deepsleep is preferred.
- If you need to control the wakelock more finely, to restrict a wakelock, nowaklock is more convenient, deepsleep can also do it but you have to check the effect with bbs.
- If you need to hide the lsposed frame, nowaklock.
- For financial applications it is more recommended to freeze rather than use the xposed framework to restrict.
